# docker-compose.yml
services:
  backend:
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
    depends_on:
      - db
  frontend:
    env_file:
      - .env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./frontend:/app
  db:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
volumes:
  postgres-data:
    driver: local
